language: node_js

node_js:
  - "lts/*"
  - "node"
  - 6

script:
  - npm run build

sudo: false

#before_script: npm run lint
#script: npm run test
#after_success: npm run coveralls

branches:
  only:
    - master
